
import os

TARGET_FILE = r"C:\Users\manum\.gemini\antigravity\scratch\gst\src\services\scrutiny_parser.py"

def fix_intentions():
    try:
        with open(TARGET_FILE, 'rb') as f:
            content = f.read().decode('utf-8')

        # 1. Fix Function Definition Indentation
        # Current: 8 spaces. Target: 4 spaces.
        bad_def = "        def _parse_import_itc_phase2"
        good_def = "    def _parse_import_itc_phase2"
        
        if bad_def in content:
            print("Found bad function definition indentation. Fixing...")
            content = content.replace(bad_def, good_def)
        else:
            print("Bad function definition not found (might match good one already).")

        # 2. Fix Call Site Indentation
        # Identify the block by the specific comment
        block_start_marker = "# 10. Point 10: Import of Goods (SOP-10) [Revised Method Call]"
        
        # We expect it to be indented by 16 spaces (double 8)
        # Because 'pre' had 8, and 'NEW_BLOCK' had 8.
        # Let's check if we can find it.
        start_idx = content.find(block_start_marker)
        if start_idx != -1:
            # Check indentation
            # Scan backwards from start_idx to newline
            line_start = content.rfind('\n', 0, start_idx) + 1
            indentation = content[line_start:start_idx]
            print(f"Call site indentation length: {len(indentation)}")
            
            if len(indentation) > 8:
                print("Call site over-indented. Dedenting block...")
                # We need to dedent lines 2020 to 2112 approx.
                # Find end of block. 
                # Block ends with "total_shortfall": 0.0\n             })
                # Check fix_sop10_callsite.py NEW_BLOCK content.
                # It ended with: })
                
                # I'll enable a robust replace:
                # Find the text chunk and replace it with dedented version.
                # I'll construct the bad chunk and good chunk.
                
                # BAD CHUNK (Generated by previous script)
                # It starts with 8 spaces in string, appended to 8 spaces in file -> 16 spaces.
                # Subsequent lines in NEW_BLOCK also had spaces.
                # Wait, newlines in NEW_BLOCK were just `\n`.
                # So subsequent lines have indentation defined in NEW_BLOCK (e.g. 5 spaces? 13 spaces?)
                # Checking `fix_sop10_callsite.py`:
                # NEW_BLOCK lines:
                # `        # 10...` (8 spaces)
                # `        analyzer_to_use...` (8 spaces)
                # So they are at 8 spaces.
                # BUT `pre` + `NEW_BLOCK`
                # `pre` ended with `\n        ` (8 spaces).
                # `NEW_BLOCK` starts with `        # 10...`
                # Combined: `\n                # 10...` (16 spaces).
                # Next line in NEW_BLOCK: starts with `\n        analyzer...`
                # So subsequent lines are at 8 spaces!
                # ONLY THE FIRST LINE IS AT 16 SPACES!
                
                # Verify this hypothesis:
                # If subsequent lines are at 8, then `analyzer_to_use` (8) matches surrounding code (8).
                # So only the comments `# 10...` etc at the top are shifted?
                # NEW_BLOCK first line: `        # 10...`
                # NEW_BLOCK second line: `        # Use updated...`
                # If pre ended with 8 spaces...
                # Line 1: 16 spaces.
                # Line 2: 8 spaces.
                # Line 3: 8 spaces.
                # Line 4: `        analyzer_to_use = ...` (8 spaces).
                 
                # This means the code `analyzer_to_use` is correctly indented at 8 spaces!
                # Only the header comments are shifted.
                # BUT `analyzer_to_use` at 8 spaces is correct.
                # So why did I suspect double indentation?
                # Because 16 spaces for comments looks bad.
                # AND `IndentationError` might happen if comments are weirdly indented? No, comments are ignored.
                
                # WAIT. `try` block or `else` block indentation.
                # `else:` line in NEW_BLOCK: `        else:` (8 spaces).
                # This should match the `if` at 8 spaces.
                # `if analyzer_to_use:` (8 spaces).
                
                # So strictly speaking, the code IS correctly indented at 8 spaces, EXCEPT the first line of the block (the comment).
                # Python doesn't care about comment indentation.
                
                # So the `IndentationError` in diagnosis was SOLELY due to the Function Definition logic (Def at 8, Body at 8).
                # I confirmed `def` was at 1341 (Function def).
                
                # So I only need to fix Step 1 (Function Definition).
                # Step 2 (Call site) might be ugly (first line indented too much) but valid code.
                # I will fix Step 1.
                pass
                
        # Write back
        with open(TARGET_FILE, 'wb') as f:
            f.write(content.encode('utf-8'))
            
        print("SUCCESS: Indentation fixed.")

    except Exception as e:
        print(f"ERROR: {e}")

if __name__ == "__main__":
    fix_intentions()
