
import sys
import os
from unittest.mock import MagicMock

# Adjust path to find src
sys.path.append(os.path.abspath("c:\\Users\\manum\\.gemini\\antigravity\\scratch\\gst"))

# Init QApplication for ScrutinyTab imports
from PyQt6.QtCore import Qt
from PyQt6.QtWebEngineWidgets import QWebEngineView # Import before app
from PyQt6.QtWidgets import QApplication

# Set attribute if needed
# QApplication.setAttribute(Qt.ApplicationAttribute.AA_ShareOpenGLContexts)

app = QApplication(sys.argv)

from src.services.scrutiny_parser import ScrutinyParser
from src.ui.scrutiny_tab import ScrutinyTab

def run_trace():
    print("--- TRACE STARTED ---")
    pdf_path = "c:\\Users\\manum\\.gemini\\antigravity\\scratch\\gst\\GSTR3B_32AAMFM4610Q1Z0_032023.pdf"
    
    # 1. Parse
    parser = ScrutinyParser()
    # Mock analyzer
    mock_analyzer = MagicMock()
    mock_analyzer.analyze_sop.return_value = {
        'tds': {'status': 'pass', 'base_value': 120000000.0}, # Diff < 0
        'tcs': {'status': 'pass', 'base_value': 0.0}
    }
    
    # We need to call parse_file, not just _parse_tds_tcs_phase2, to hit the "Final Payload" log.
    # Note: parse_file needs Phase-2 analyzer for SOP-5.
    
    print("\n[STEP 1] Running ScrutinyParser.parse_file...")
    
    # Simulate Real Scenario: Primary is Excel, 3B PDF is in extra_files
    primary_excel = "D:/My Analysis/Tax_Liability.xlsx"
    files = {
        "gstr3b_yearly": pdf_path, # This is the valid PDF path defined at top
        "gstr2a_yearly": "gstr2a.xlsx"
    }
    
    # Pass extra_files
    result = parser.parse_file(primary_excel, gstr2a_analyzer=mock_analyzer, extra_files=files)
    
    issues = result['issues']
    # Filter to only SOP-5 to avoid crashes on other issues with bad mock data
    sop5_issue = next((i for i in issues if i.get('issue_id') == "TDS_TCS_MISMATCH"), None)
    if not sop5_issue:
        print("CRITICAL: SOP-5 Issue NOT generated by parser.")
        return

    # 2. Enrich
    print("\n[STEP 2] Simulating ScrutinyTab.enrich_issues_with_templates...")
    
    # Mock DB
    mock_db = MagicMock()
    mock_db.get_issue.return_value = {
        "issue_id": "TDS_TCS_MISMATCH",
        "issue_name": "TDS/TCS Mismatch",
        "sop_point": 5,
        "grid_data": [{"col0": "Simulated Legacy Grid Cell"}] 
    }
    
    # Mock Tab
    class TestTab(ScrutinyTab):
        def __init__(self, db):
            self.db = db
            # Skip super init
            pass
            
    tab = TestTab(mock_db)
        
    enriched_issues = tab.enrich_issues_with_templates([sop5_issue])
    
    sop5_enriched = next((i for i in enriched_issues if i.get('issue_id') == "TDS_TCS_MISMATCH"), None)
    print(f"\n[FINAL RESULT] SOP-5 Enriched Tables: {sop5_enriched.get('tables')}")
    print(f"[FINAL RESULT] SOP-5 Enriched Grid: {sop5_enriched.get('grid_data')}")

if __name__ == "__main__":
    try:
        run_trace()
    except Exception as e:
        print(f"TRACE CRASHED: {e}")
        import traceback
        traceback.print_exc()
